import { useMemo } from "react";
import { Download, ExternalLink, Filter, MessageSquareText, RefreshCw, Star, Tag, TrendingUp, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { SHOP } from "@shared/business";

function sentimentColor(sentiment: string) { return sentiment === "positive" ? "bg-[#e6f0c5] text-[#58701e]" : sentiment === "negative" ? "bg-[#fff2ef] text-[#9a4b35]" : "bg-[#ecece4] text-[#657068]"; }
function csvEscape(value: unknown) { return `"${String(value ?? "").replaceAll('"', '""')}"`; }

export default function Dashboard() {
  const summaryQuery = trpc.feedback.summary.useQuery(undefined, { refetchInterval: 10000 });
  const exportQuery = trpc.feedback.exportRows.useQuery(undefined, { enabled: false });
  const data = summaryQuery.data;
  const topTags = useMemo(() => Object.entries(data?.tagCounts ?? {}).sort(([, a], [, b]) => b - a).slice(0, 5), [data?.tagCounts]);
  const maxTrend = Math.max(...(data?.trend.map((item) => item.count) ?? [1]), 1);

  const downloadCsv = async () => {
    try {
      const result = await exportQuery.refetch();
      const rows = result.data ?? [];
      if (!rows.length) { toast.info("There are no feedback records to export yet."); return; }
      const header = ["createdAt", "customerName", "customerContact", "rating", "npsScore", "serviceType", "sentiment", "tags", "comment", "source", "followUp", "status"];
      const body = rows.map((row) => header.map((key) => csvEscape(row[key as keyof typeof row])).join(","));
      const blob = new Blob([[header.join(","), ...body].join("\n")], { type: "text/csv;charset=utf-8" });
      const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `harsh-computers-feedback-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); toast.success("CSV export downloaded.");
    } catch { toast.error("Export is available to the shop owner account only."); }
  };

  return <div className="space-y-7">
    <div className="flex flex-col gap-4 border-b border-[#202326]/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b74337]">Harsh Computers</p><h1 className="mt-2 font-serif text-4xl tracking-[-0.045em] text-[#202326]">Feedback dashboard</h1><p className="mt-2 text-sm text-[#6b6f72]">Ratings, comments, and follow-up requests in one place.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => summaryQuery.refetch()} className="rounded-full border-[#202326]/15 bg-white"><RefreshCw className={`mr-2 h-4 w-4 ${summaryQuery.isFetching ? "animate-spin" : ""}`} />Refresh</Button><Button onClick={downloadCsv} disabled={exportQuery.isFetching} className="rounded-full bg-[#b74337] text-white hover:bg-[#96352e]"><Download className="mr-2 h-4 w-4" />Export CSV</Button></div></div>
    {summaryQuery.isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map((item) => <div key={item} className="h-32 animate-pulse rounded-2xl bg-[#e6e6dc]" />)}</div> : <>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Responses" value={data?.total ?? 0} detail="all time" icon={<MessageSquareText className="h-5 w-5" />} accent="lime" /><StatCard label="Average rating" value={`${data?.avgRating ?? 0}/5`} detail={`Google profile: ${SHOP.rating}/5`} icon={<Star className="h-5 w-5 fill-current" />} accent="gold" /><StatCard label="NPS score" value={data?.nps ?? 0} detail={`${data?.promoters ?? 0} promoters · ${data?.detractors ?? 0} detractors`} icon={<TrendingUp className="h-5 w-5" />} accent="blue" /><StatCard label="Needs follow-up" value={data?.followUps ?? 0} detail="open loops" icon={<UsersRound className="h-5 w-5" />} accent="peach" /></div>
      <div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><Card className="rounded-2xl border-[#202326]/10 bg-white shadow-sm"><CardHeader className="flex flex-row items-start justify-between space-y-0"><div><CardTitle className="font-serif text-2xl text-[#202326]">Response rhythm</CardTitle><p className="mt-1 text-sm text-[#78847d]">Last 7 days · response count</p></div><Badge className="bg-[#f8e2de] text-[#96352e] hover:bg-[#f8e2de]">Live</Badge></CardHeader><CardContent><div className="flex h-52 items-end gap-3 pt-6">{(data?.trend ?? []).map((item) => <div key={item.label} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-36 w-full items-end"><div className="w-full rounded-t-xl bg-[#e4aaa1] transition-all" style={{ height: `${Math.max((item.count / maxTrend) * 100, item.count ? 14 : 4)}%` }} title={`${item.count} responses`} /></div><span className="text-xs text-[#829087]">{item.label}</span><span className="text-xs font-semibold text-[#202326]">{item.count}</span></div>)}</div></CardContent></Card><Card className="rounded-2xl border-[#202326]/10 bg-white shadow-sm"><CardHeader><CardTitle className="font-serif text-2xl text-[#202326]">Sentiment mix</CardTitle><p className="mt-1 text-sm text-[#78847d]">Derived from rating + comments</p></CardHeader><CardContent><div className="space-y-5">{([["positive", data?.sentiment.positive ?? 0, "bg-[#b74337]"], ["neutral", data?.sentiment.neutral ?? 0, "bg-[#b7b9ba]"], ["negative", data?.sentiment.negative ?? 0, "bg-[#d17d6e"]] as const).map(([label, count, color]) => <div key={label}><div className="mb-2 flex justify-between text-sm"><span className="capitalize font-semibold text-[#526259]">{label}</span><span className="font-bold text-[#202326]">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-[#edf0e9]"><div className={`h-full rounded-full ${color}`} style={{ width: `${data?.total ? Math.max((count / data.total) * 100, count ? 6 : 0) : 0}%` }} /></div></div>)}<div className="mt-7 rounded-xl bg-[#f2f4ec] p-4"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#7b8d6e]">NPS breakdown</p><div className="mt-3 flex justify-between text-sm"><span className="text-[#58701e]">Promoters <strong>{data?.promoters ?? 0}</strong></span><span className="text-[#6f7a72]">Passives <strong>{data?.passives ?? 0}</strong></span><span className="text-[#9a4b35]">Detractors <strong>{data?.detractors ?? 0}</strong></span></div></div></div></CardContent></Card></div>
      <div className="grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><Card className="rounded-2xl border-[#202326]/10 bg-white shadow-sm"><CardHeader><CardTitle className="font-serif text-2xl text-[#202326]">What customers notice</CardTitle><p className="mt-1 text-sm text-[#78847d]">Most-used response tags</p></CardHeader><CardContent><div className="space-y-4">{topTags.length ? topTags.map(([tag, count]) => <div key={tag} className="flex items-center justify-between rounded-xl bg-[#f3f3f1] px-4 py-3"><span className="flex items-center gap-2 text-sm font-semibold text-[#526259]"><Tag className="h-4 w-4 text-[#b74337]" />{tag}</span><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-[#202326]">{count}</span></div>) : <EmptyState text="Tags will appear after the first response." />}</div><div className="mt-7 border-t border-[#202326]/10 pt-5"><p className="mb-3 text-xs font-bold uppercase tracking-[0.15em] text-[#7b8d6e]">Service mix</p><div className="flex flex-wrap gap-2">{Object.entries(data?.serviceCounts ?? {}).map(([service, count]) => <Badge key={service} variant="outline" className="border-[#202326]/15 text-[#5e6d64]">{service} · {count}</Badge>)}</div></div></CardContent></Card><Card className="rounded-2xl border-[#202326]/10 bg-white shadow-sm"><CardHeader className="flex flex-row items-start justify-between space-y-0"><div><CardTitle className="font-serif text-2xl text-[#202326]">Latest responses</CardTitle><p className="mt-1 text-sm text-[#78847d]">Newest feedback from the floor</p></div><Filter className="h-5 w-5 text-[#9aaa5e]" /></CardHeader><CardContent><div className="space-y-3">{data?.recent.length ? data.recent.map((row) => <div key={row.id} className="rounded-xl border border-[#202326]/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#202326]">{row.customerName || "Anonymous customer"}</p><p className="mt-1 text-xs text-[#859188]">{row.serviceType} · {new Date(row.createdAt).toLocaleDateString("en-IN")}</p></div><div className="text-right"><p className="text-sm font-bold text-[#c99436]">{"★".repeat(row.rating)}<span className="text-[#d6dcd4]">{"★".repeat(5 - row.rating)}</span></p><Badge className={`mt-1 ${sentimentColor(row.sentiment)} hover:${sentimentColor(row.sentiment)}`}>{row.sentiment}</Badge></div></div>{row.comment && <p className="mt-3 text-sm leading-6 text-[#5f6e65]">“{row.comment}”</p>}</div>) : <EmptyState text="Your first response will appear here." />}</div></CardContent></Card></div>
    </>}
    <p className="text-xs text-[#8a958e]">Dashboard data refreshes every 10 seconds. Google rating is sourced from the public business listing and is separate from private survey responses. <a href={SHOP.mapsUrl} target="_blank" rel="noreferrer" className="font-semibold text-[#96352e] hover:underline">View listing <ExternalLink className="ml-1 inline h-3 w-3" /></a></p>
  </div>;
}

function StatCard({ label, value, detail, icon, accent }: { label: string; value: string | number; detail: string; icon: React.ReactNode; accent: "lime" | "gold" | "blue" | "peach" }) { const colors = { lime: "bg-[#f8e2de] text-[#58701e]", gold: "bg-[#faefd0] text-[#9b7122]", blue: "bg-[#e7ecee] text-[#3e6e67]", peach: "bg-[#fff2ef] text-[#9a4b35]" }; return <Card className="rounded-2xl border-[#202326]/10 bg-white shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-[#78847d]">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-[#202326]">{value}</p><p className="mt-1 text-xs text-[#8b968f]">{detail}</p></div><div className={`grid h-10 w-10 place-items-center rounded-xl ${colors[accent]}`}>{icon}</div></div></CardContent></Card>; }
function EmptyState({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-[#202326]/15 px-4 py-8 text-center text-sm text-[#89958d]">{text}</div>; }
